Feature/telemetry
kubeshark/hub pull request #4
Opened 2023-08-08 19:25 UTC by manfioLP

2023-08-24 19:57 UTC, manfioLP commented
Moving this to different separate repository @ kubeshark/telemetry

2023-08-25 17:29 UTC, mertyildiran requested changes

2023-08-25 17:29 UTC, mertyildiran commented on main.go
> +var telemetryDisabled = flag.Bool("no-telemetry", false, "Disables telemetry data usage")
```suggestion
```

Don't create a new flag, but instead define and read an environment variable in here:

https://github.com/kubeshark/hub/blob/d438c094b67e3f1751610e732f6938668e42e5af/main.go#L28-L37

like;

```go
        ENV_TELEMETRY_DISABLED          = "TELEMETRY_DISABLED"
```

Because it's hard to deliver a flag smoothly since the Helm chart and the image decoupled to a degree.

Also add that environment to `run` Makefile rule:

https://github.com/kubeshark/hub/blob/d438c094b67e3f1751610e732f6938668e42e5af/Makefile#L22-L23

Like: 

```Makefile
run: ## Run the program. Requires Worker being available on port 8897
	TELEMETRY_DISABLED=true ./hub -port 8898 -debug
```

2023-08-25 17:29 UTC, mertyildiran commented on main.go
> +	}
```suggestion
	go sendTelemetry(*telemetryDisabled)
```

I would move this check into `sendTelemetry` method's itself and turn it into a guard clause instead.

2023-08-25 17:29 UTC, mertyildiran commented on main.go
> +		telemetry.Run(startTime, clientset, "kubeshark-hub")
```suggestion
		telemetry.Run(startTime, K8sWatcher.clientSet, "kubeshark-hub")
```

Pass the `*kubernetes.Clientset` created in here:

https://github.com/kubeshark/hub/blob/d438c094b67e3f1751610e732f6938668e42e5af/pkg/kubernetes/loader.go#L19

2023-08-25 17:29 UTC, mertyildiran commented on main.go
> +	}
```suggestion
```

Don't create a new `clientSet` (also camelCase) in here. But instead use the `*kubernetes.Clientset` created in here:

https://github.com/kubeshark/hub/blob/d438c094b67e3f1751610e732f6938668e42e5af/pkg/kubernetes/loader.go#L19

2023-08-25 17:29 UTC, mertyildiran commented on go.mod
> +	k8s.io/client-go v0.28.1
```suggestion
	github.com/rs/zerolog v1.29.0
	k8s.io/api v0.27.2
	k8s.io/apimachinery v0.27.2
	k8s.io/client-go v0.27.2
```

Don't change these version with this PR to prevent creating a huge diff in `go.sum`. In order to do that, use the same versions in here: https://github.com/kubeshark/telemetry/blob/master/go.mod#L6-L9

2023-08-28 03:53 UTC, manfioLP commented on main.go
> +var telemetryDisabled = flag.Bool("no-telemetry", false, "Disables telemetry data usage")
done, good to know about the flags and helm charts.

just to confirm: `make run` is used to run locally only, right?

2023-08-28 04:04 UTC, manfioLP commented on main.go
> +	}
done, good suggestion

2023-08-28 04:11 UTC, manfioLP commented on main.go
> +		telemetry.Run(startTime, clientset, "kubeshark-hub")
for this it needs to change struct `K8sWatcher` to have ClientSet exported.

done, I think this won't cause any sideeffects, right?

2023-08-28 04:16 UTC, manfioLP commented on main.go
> +	}
using export ClientSet from K8sWatcher now.

2023-08-28 04:20 UTC, manfioLP commented on go.mod
> +	k8s.io/client-go v0.28.1
my bad, I think it likely got upgraded when running go mod / tidy. Reverted.

2023-08-29 03:25 UTC, manfioLP commented on main.go
> +		telemetry.Run(startTime, clientset, "kubeshark-hub")
for the record, I'm creating a getter function for clientSet so we dont need to export it

2023-08-29 23:36 UTC, mertyildiran approved these changes

2023-08-29 23:36 UTC, merged